#!/usr/bin/env python3
import os, shutil, json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parent
HTML=(ROOT/'index.html').read_text()
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    for width in [1440,1024,768,390,320]:
        page=browser.new_page(viewport={'width':width,'height':950},accept_downloads=True)
        errors=[];requests=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.on('request',lambda r:requests.append(r.url))
        page.set_content(HTML)
        expect(page.locator('#setupTitle')).to_have_text('給与・賞与')
        expect(page.locator('#simResults')).to_be_hidden()
        expect(page.locator('#simAge')).to_be_hidden()
        page.locator('#monthlyGross').fill('1')
        page.locator('#setupNext').click()
        expect(page.locator('#setupProgress')).to_have_text('1 / 5')
        expect(page.locator('#setupError')).to_be_visible()
        page.locator('#monthlyGross').fill('330000')
        page.locator('#monthlyGross').press('Enter')
        expect(page.locator('#setupTitle')).to_have_text('社会保険')
        expect(page.locator('#setupTitle')).to_be_focused()
        expect(page.locator('label[for="simPrefecture"]')).to_have_text('勤務先の所在地（都道府県）')
        expect(page.locator('#standardMode')).to_be_hidden()
        page.locator('#setupStandardOptions>summary').click()
        page.locator('#standardMode').select_option('manual')
        expect(page.locator('#healthStandard')).to_be_visible()
        page.locator('#standardMode').select_option('auto')
        page.locator('#setupStandardOptions>summary').click()
        # Regression: unfinished later step must remain reachable after Back.
        page.locator('#simAge').fill('')
        page.locator('#setupBack').click()
        page.locator('#setupNext').click()
        expect(page.locator('#setupTitle')).to_have_text('社会保険')
        page.locator('#setupNext').click()
        expect(page.locator('#setupTitle')).to_have_text('社会保険')
        expect(page.locator('#simAge')).to_be_focused()
        page.locator('#simAge').fill('42')
        page.locator('#simEmployment').select_option('0')
        page.locator('#setupBack').click()
        expect(page.locator('#monthlyGross')).to_have_value('330000')
        page.locator('#setupNext').click()
        expect(page.locator('#simAge')).to_have_value('42')
        page.locator('#setupNext').click()
        page.locator('#dependentConditions>summary').click()
        page.locator('#dependent_young').fill('1')
        page.locator('#dependent_under16').fill('10')
        page.locator('#setupNext').click()
        page.locator('#monthlyResidentMode').select_option('none')
        page.locator('#simResidentMode').select_option('manual')
        page.locator('#simResidentAnnual').fill('210000')
        page.locator('#setupNext').click()
        # Each count is valid, but the combined family limit must block completion.
        page.locator('#setupNext').click()
        expect(page.locator('#setupProgress')).to_have_text('5 / 5')
        expect(page.locator('#setupError')).to_be_visible()
        expect(page.locator('#simResults')).to_be_hidden()
        page.locator('#setupBack').click()
        page.locator('#setupBack').click()
        page.locator('#dependent_under16').fill('0')
        page.locator('#setupNext').click()
        page.locator('#setupNext').click()
        expect(page.locator('#setupPanel4')).to_contain_text('330,000円')
        expect(page.locator('#setupPanel4')).to_contain_text('天引きしない')
        assert not page.evaluate('document.documentElement.scrollWidth>innerWidth')
        if width==390:page.screenshot(path='/tmp/nenshu-wizard-review.png',full_page=True)
        page.locator('#setupNext').click()
        expect(page.locator('#simResults')).to_be_visible()
        expect(page.locator('#setupWizard')).to_be_hidden()
        expect(page.locator('#socialModelNote')).to_contain_text('協会けんぽ（東京都支部）')
        expect(page.locator('#socialModelNote')).to_contain_text('標準報酬月額は入力した月給からの概算')
        with page.expect_download() as download:page.locator('#simSave').click()
        saved=json.loads(Path(download.value.path()).read_text())
        assert saved['input']['monthlyResidentMode']=='none'
        assert saved['input']['dependents']['young']==1
        expected=page.evaluate('(doc)=>Nenshu.calculate(doc.input,doc.policy).monthly.net',saved)
        expect(page.locator('#monthlyNet')).to_have_text(f'{expected:,}円')
        assert page.locator('#setupLaunch').evaluate('(el)=>el.tabIndex')==0
        page.locator('#salaryConditions').evaluate('(e)=>e.open=true');page.locator('#setupLaunch').click()
        expect(page.locator('#monthlyGross')).to_have_value('330000')
        # Import while in the wizard updates the same controls and preserves the flow.
        page.locator('#simFile').set_input_files({'name':'settings.json','mimeType':'application/json','buffer':json.dumps(saved).encode()})
        expect(page.locator('#toast')).to_contain_text('設定を読み込みました')
        # Load manual grades into an already-active wizard and reveal them.
        saved['input'].update(standardMode='manual',healthStandard=280000,pensionStandard=280000)
        page.locator('#simFile').set_input_files({'name':'manual.json','mimeType':'application/json','buffer':json.dumps(saved).encode()})
        expect(page.locator('#standardMode')).to_have_value('manual')
        page.locator('#setupNext').click()
        expect(page.locator('#healthStandard')).to_be_visible()
        expect(page.locator('#healthStandard')).to_have_value('280000')
        expect(page.locator('#pensionStandard')).to_have_value('280000')
        saved['input']['standardMode']='auto'
        page.locator('#simFile').set_input_files({'name':'auto.json','mimeType':'application/json','buffer':json.dumps(saved).encode()})
        expect(page.locator('#standardMode')).to_have_value('auto')
        page.locator('#setupNext').click()
        expect(page.locator('#standardMode')).to_be_hidden()
        page.locator('#setupAll').click();page.locator('#breakdownItems').evaluate('(e)=>e.open=true')
        expect(page.locator('#simResults')).to_be_visible()
        assert not errors,errors
        assert not requests,requests
        assert page.locator('#monthlyGross').count()==1
        print('PASS setup wizard',width,flush=True)
        page.close()
    browser.close()
